name: mamba-cuda
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pytorch::pytorch>=2.0.0
  - pytorch::pytorch-cuda=12.1
  - nvidia::cuda-toolkit=12.1
  - conda-forge::ninja
  - pip
  - pip:
      - triton>=2.1.0
      - einops
      - transformers
      - packaging
      - pytest
      - causal-conv1d>=1.2.0

